// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SionFashioWebApplicationMVC.Datos;

#nullable disable

namespace SionFashioWebApplicationMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240920204604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.alertas_stock", b =>
                {
                    b.Property<int>("id_alerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_alerta"));

                    b.Property<DateTime>("fecha_alerta")
                        .HasColumnType("datetime");

                    b.Property<int>("id_producto")
                        .HasColumnType("int");

                    b.Property<int>("nivel_minimo")
                        .HasColumnType("int");

                    b.HasKey("id_alerta")
                        .HasName("PK__alertas___1227953EE8C191DA");

                    b.HasIndex("id_producto");

                    b.ToTable("alertas_stock");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.categoria", b =>
                {
                    b.Property<int>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_categoria"));

                    b.Property<string>("nombre_categoria")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id_categoria")
                        .HasName("PK__categori__CD54BC5A96EC1E1C");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.ciudade", b =>
                {
                    b.Property<int>("id_ciudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_ciudad"));

                    b.Property<int>("id_departamento")
                        .HasColumnType("int");

                    b.Property<string>("nombre_ciudad")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id_ciudad")
                        .HasName("PK__ciudades__B7DC4CD57E899779");

                    b.HasIndex("id_departamento");

                    b.ToTable("ciudades");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.cliente", b =>
                {
                    b.Property<int>("id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_cliente"));

                    b.Property<string>("direccion_cliente")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("email_cliente")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("nombre_cliente")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("telefono_cliente")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id_cliente")
                        .HasName("PK__clientes__677F38F5A41537AF");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.departamento", b =>
                {
                    b.Property<int>("id_departamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_departamento"));

                    b.Property<int>("id_pais")
                        .HasColumnType("int");

                    b.Property<string>("nombre_departamento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id_departamento")
                        .HasName("PK__departam__64F37A166A6421AB");

                    b.HasIndex("id_pais");

                    b.ToTable("departamentos");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.empleado", b =>
                {
                    b.Property<int>("id_empleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_empleado"));

                    b.Property<string>("apellidos_empleado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("dni_empleado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("email_empleado")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("id_ciudad")
                        .HasColumnType("int");

                    b.Property<int?>("id_tienda")
                        .HasColumnType("int");

                    b.Property<string>("nombres_empleado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("telefono_empleado")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id_empleado")
                        .HasName("PK__empleado__88B513944BCC5AFB");

                    b.HasIndex("id_ciudad");

                    b.HasIndex("id_tienda");

                    b.HasIndex(new[] { "dni_empleado" }, "UQ__empleado__0FA5136F97BC99B9")
                        .IsUnique();

                    b.ToTable("empleados");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.empresa", b =>
                {
                    b.Property<int>("id_empresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_empresa"));

                    b.Property<string>("direccion_empresa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("email_empresa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("nombre_empresa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("telefono_empresa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id_empresa")
                        .HasName("PK__empresas__4A0B7E2CBF58E78F");

                    b.ToTable("empresas");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.factura", b =>
                {
                    b.Property<int>("id_factura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_factura"));

                    b.Property<DateTime>("fecha_emision_factura")
                        .HasColumnType("datetime");

                    b.Property<int>("id_cliente")
                        .HasColumnType("int");

                    b.Property<decimal>("impuesto_factura")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("sub_total_factura")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("total_factura")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("id_factura")
                        .HasName("PK__facturas__6C08ED53AD2D0B61");

                    b.HasIndex("id_cliente");

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.historial_inventario", b =>
                {
                    b.Property<int>("id_historial_inventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_historial_inventario"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_cambio")
                        .HasColumnType("datetime");

                    b.Property<int>("id_producto")
                        .HasColumnType("int");

                    b.Property<string>("tipo_cambio")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id_historial_inventario")
                        .HasName("PK__historia__7B04571419F1DF4B");

                    b.HasIndex("id_producto");

                    b.ToTable("historial_inventario");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.inventario", b =>
                {
                    b.Property<int>("id_producto")
                        .HasColumnType("int");

                    b.Property<int>("saldo")
                        .HasColumnType("int");

                    b.Property<int>("stock_actual")
                        .HasColumnType("int");

                    b.Property<int>("stock_inicial")
                        .HasColumnType("int");

                    b.HasKey("id_producto")
                        .HasName("PK__inventar__FF341C0DF584C001");

                    b.ToTable("inventario");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.metodos_de_pago", b =>
                {
                    b.Property<int>("id_metodo_pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_metodo_pago"));

                    b.Property<int?>("id_factura")
                        .HasColumnType("int");

                    b.Property<string>("metodo_pago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_metodo_pago")
                        .HasName("PK__metodos___85BE0EBC43A100D9");

                    b.HasIndex("id_factura");

                    b.ToTable("metodos_de_pago");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.ordenes_de_compra", b =>
                {
                    b.Property<int>("id_orden_compra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_orden_compra"));

                    b.Property<int>("id_cliente")
                        .HasColumnType("int");

                    b.Property<int?>("id_empleado")
                        .HasColumnType("int");

                    b.Property<int?>("id_factura")
                        .HasColumnType("int");

                    b.HasKey("id_orden_compra")
                        .HasName("PK__ordenes___71B729AF010BC7FC");

                    b.HasIndex("id_cliente");

                    b.HasIndex("id_empleado");

                    b.HasIndex("id_factura");

                    b.ToTable("ordenes_de_compra");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.ordenes_producto", b =>
                {
                    b.Property<int>("id_orden_compra")
                        .HasColumnType("int");

                    b.Property<int>("id_producto")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.HasKey("id_orden_compra", "id_producto")
                        .HasName("PK__ordenes___BE44686FC1FB969A");

                    b.HasIndex("id_producto");

                    b.ToTable("ordenes_productos");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.paise", b =>
                {
                    b.Property<int>("id_pais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_pais"));

                    b.Property<string>("nombre_pais")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id_pais")
                        .HasName("PK__paises__0941A3A73CFF96F9");

                    b.ToTable("paises");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.producto", b =>
                {
                    b.Property<int>("id_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_producto"));

                    b.Property<string>("descripcion_producto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("id_factura")
                        .HasColumnType("int");

                    b.Property<int>("id_proveedor")
                        .HasColumnType("int");

                    b.Property<int>("id_sub_categoria")
                        .HasColumnType("int");

                    b.Property<int>("id_tienda")
                        .HasColumnType("int");

                    b.Property<string>("nombre_producto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("peso_del_producto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("precio_producto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ubicacion_producto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("unidad_medida")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("id_producto")
                        .HasName("PK__producto__FF341C0D3973994B");

                    b.HasIndex("id_factura");

                    b.HasIndex("id_proveedor");

                    b.HasIndex("id_sub_categoria");

                    b.HasIndex("id_tienda");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.proveedore", b =>
                {
                    b.Property<int>("id_proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_proveedor"));

                    b.Property<string>("contacto_proveedor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("email_proveedor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("id_ciudad")
                        .HasColumnType("int");

                    b.Property<string>("nombre_proveedor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id_proveedor")
                        .HasName("PK__proveedo__9B1A7A4DC0FB78C7");

                    b.HasIndex("id_ciudad");

                    b.ToTable("proveedores");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.registros_actividade", b =>
                {
                    b.Property<int>("id_registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_registro"));

                    b.Property<string>("actividad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_actividad")
                        .HasColumnType("datetime");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.HasKey("id_registro")
                        .HasName("PK__registro__AFB90F854AF83AE6");

                    b.HasIndex("id_usuario");

                    b.ToTable("registros_actividades");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.role", b =>
                {
                    b.Property<int>("id_rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_rol"));

                    b.Property<string>("descripcion_rol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_rol")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id_rol")
                        .HasName("PK__roles__DC7B66356B9BBF18");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.sub_categoria", b =>
                {
                    b.Property<int>("id_sub_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_sub_categoria"));

                    b.Property<int>("id_categoria")
                        .HasColumnType("int");

                    b.Property<string>("nombre_sub_categoria")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id_sub_categoria")
                        .HasName("PK__sub_cate__3D86594DAD32418F");

                    b.HasIndex("id_categoria");

                    b.ToTable("sub_categorias");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.tienda", b =>
                {
                    b.Property<int>("id_tienda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tienda"));

                    b.Property<int>("id_ciudad")
                        .HasColumnType("int");

                    b.Property<int>("id_empresa")
                        .HasColumnType("int");

                    b.Property<string>("nombre_tienda")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("telefono_tienda")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ubicacion_tienda")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id_tienda")
                        .HasName("PK__tiendas__B672D3141F40D5C7");

                    b.HasIndex("id_ciudad");

                    b.HasIndex("id_empresa");

                    b.ToTable("tiendas");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("clave_usuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("id_rol")
                        .HasColumnType("int");

                    b.Property<string>("nombre_usuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id_usuario")
                        .HasName("PK__usuarios__4E3E04AD9445F62E");

                    b.HasIndex("id_rol");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.alertas_stock", b =>
                {
                    b.HasOne("SionFashioWebApplicationMVC.Models.producto", "id_productoNavigation")
                        .WithMany("alertas_stocks")
                        .HasForeignKey("id_producto")
                        .IsRequired()
                        .HasConstraintName("FK__alertas_s__id_pr__6EF57B66");

                    b.Navigation("id_productoNavigation");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.ciudade", b =>
                {
                    b.HasOne("SionFashioWebApplicationMVC.Models.departamento", "id_departamentoNavigation")
                        .WithMany("ciudades")
                        .HasForeignKey("id_departamento")
                        .IsRequired()
                        .HasConstraintName("FK__ciudades__id_dep__3C69FB99");

                    b.Navigation("id_departamentoNavigation");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.departamento", b =>
                {
                    b.HasOne("SionFashioWebApplicationMVC.Models.paise", "id_paisNavigation")
                        .WithMany("departamentos")
                        .HasForeignKey("id_pais")
                        .IsRequired()
                        .HasConstraintName("FK__departame__id_pa__398D8EEE");

                    b.Navigation("id_paisNavigation");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.empleado", b =>
                {
                    b.HasOne("SionFashioWebApplicationMVC.Models.ciudade", "id_ciudadNavigation")
                        .WithMany("empleados")
                        .HasForeignKey("id_ciudad")
                        .HasConstraintName("FK__empleados__id_ci__4E88ABD4");

                    b.HasOne("SionFashioWebApplicationMVC.Models.tienda", "id_tiendaNavigation")
                        .WithMany("empleados")
                        .HasForeignKey("id_tienda")
                        .HasConstraintName("FK__empleados__id_ti__4D94879B");

                    b.Navigation("id_ciudadNavigation");

                    b.Navigation("id_tiendaNavigation");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.factura", b =>
                {
                    b.HasOne("SionFashioWebApplicationMVC.Models.cliente", "id_clienteNavigation")
                        .WithMany("facturas")
                        .HasForeignKey("id_cliente")
                        .IsRequired()
                        .HasConstraintName("FK__facturas__id_cli__534D60F1");

                    b.Navigation("id_clienteNavigation");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.historial_inventario", b =>
                {
                    b.HasOne("SionFashioWebApplicationMVC.Models.producto", "id_productoNavigation")
                        .WithMany("historial_inventarios")
                        .HasForeignKey("id_producto")
                        .IsRequired()
                        .HasConstraintName("FK__historial__id_pr__6C190EBB");

                    b.Navigation("id_productoNavigation");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.inventario", b =>
                {
                    b.HasOne("SionFashioWebApplicationMVC.Models.producto", "id_productoNavigation")
                        .WithOne("inventario")
                        .HasForeignKey("SionFashioWebApplicationMVC.Models.inventario", "id_producto")
                        .IsRequired()
                        .HasConstraintName("FK__inventari__id_pr__68487DD7");

                    b.Navigation("id_productoNavigation");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.metodos_de_pago", b =>
                {
                    b.HasOne("SionFashioWebApplicationMVC.Models.factura", "id_facturaNavigation")
                        .WithMany("metodos_de_pagos")
                        .HasForeignKey("id_factura")
                        .HasConstraintName("FK__metodos_d__id_fa__619B8048");

                    b.Navigation("id_facturaNavigation");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.ordenes_de_compra", b =>
                {
                    b.HasOne("SionFashioWebApplicationMVC.Models.cliente", "id_clienteNavigation")
                        .WithMany("ordenes_de_compras")
                        .HasForeignKey("id_cliente")
                        .IsRequired()
                        .HasConstraintName("FK__ordenes_d__id_cl__5629CD9C");

                    b.HasOne("SionFashioWebApplicationMVC.Models.empleado", "id_empleadoNavigation")
                        .WithMany("ordenes_de_compras")
                        .HasForeignKey("id_empleado")
                        .HasConstraintName("FK__ordenes_d__id_em__5812160E");

                    b.HasOne("SionFashioWebApplicationMVC.Models.factura", "id_facturaNavigation")
                        .WithMany("ordenes_de_compras")
                        .HasForeignKey("id_factura")
                        .HasConstraintName("FK__ordenes_d__id_fa__571DF1D5");

                    b.Navigation("id_clienteNavigation");

                    b.Navigation("id_empleadoNavigation");

                    b.Navigation("id_facturaNavigation");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.ordenes_producto", b =>
                {
                    b.HasOne("SionFashioWebApplicationMVC.Models.ordenes_de_compra", "id_orden_compraNavigation")
                        .WithMany("ordenes_productos")
                        .HasForeignKey("id_orden_compra")
                        .IsRequired()
                        .HasConstraintName("FK__ordenes_p__id_or__6477ECF3");

                    b.HasOne("SionFashioWebApplicationMVC.Models.producto", "id_productoNavigation")
                        .WithMany("ordenes_productos")
                        .HasForeignKey("id_producto")
                        .IsRequired()
                        .HasConstraintName("FK__ordenes_p__id_pr__656C112C");

                    b.Navigation("id_orden_compraNavigation");

                    b.Navigation("id_productoNavigation");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.producto", b =>
                {
                    b.HasOne("SionFashioWebApplicationMVC.Models.factura", "id_facturaNavigation")
                        .WithMany("productos")
                        .HasForeignKey("id_factura")
                        .HasConstraintName("FK__productos__id_fa__5DCAEF64");

                    b.HasOne("SionFashioWebApplicationMVC.Models.proveedore", "id_proveedorNavigation")
                        .WithMany("productos")
                        .HasForeignKey("id_proveedor")
                        .IsRequired()
                        .HasConstraintName("FK__productos__id_pr__5BE2A6F2");

                    b.HasOne("SionFashioWebApplicationMVC.Models.sub_categoria", "id_sub_categoriaNavigation")
                        .WithMany("productos")
                        .HasForeignKey("id_sub_categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SionFashioWebApplicationMVC.Models.tienda", "id_tiendaNavigation")
                        .WithMany("productos")
                        .HasForeignKey("id_tienda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("id_facturaNavigation");

                    b.Navigation("id_proveedorNavigation");

                    b.Navigation("id_sub_categoriaNavigation");

                    b.Navigation("id_tiendaNavigation");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.proveedore", b =>
                {
                    b.HasOne("SionFashioWebApplicationMVC.Models.ciudade", "id_ciudadNavigation")
                        .WithMany("proveedores")
                        .HasForeignKey("id_ciudad")
                        .HasConstraintName("FK__proveedor__id_ci__46E78A0C");

                    b.Navigation("id_ciudadNavigation");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.registros_actividade", b =>
                {
                    b.HasOne("SionFashioWebApplicationMVC.Models.usuario", "id_usuarioNavigation")
                        .WithMany("registros_actividades")
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("id_usuarioNavigation");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.sub_categoria", b =>
                {
                    b.HasOne("SionFashioWebApplicationMVC.Models.categoria", "id_categoriaNavigation")
                        .WithMany("sub_categoria")
                        .HasForeignKey("id_categoria")
                        .IsRequired()
                        .HasConstraintName("FK__sub_categ__id_ca__0F624AF8");

                    b.Navigation("id_categoriaNavigation");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.tienda", b =>
                {
                    b.HasOne("SionFashioWebApplicationMVC.Models.ciudade", "id_ciudadNavigation")
                        .WithMany("tienda")
                        .HasForeignKey("id_ciudad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SionFashioWebApplicationMVC.Models.empresa", "id_empresaNavigation")
                        .WithMany("tienda")
                        .HasForeignKey("id_empresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("id_ciudadNavigation");

                    b.Navigation("id_empresaNavigation");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.usuario", b =>
                {
                    b.HasOne("SionFashioWebApplicationMVC.Models.role", "id_rolNavigation")
                        .WithMany("usuarios")
                        .HasForeignKey("id_rol")
                        .IsRequired()
                        .HasConstraintName("FK__usuarios__id_rol__5FB337D6");

                    b.Navigation("id_rolNavigation");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.categoria", b =>
                {
                    b.Navigation("sub_categoria");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.ciudade", b =>
                {
                    b.Navigation("empleados");

                    b.Navigation("proveedores");

                    b.Navigation("tienda");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.cliente", b =>
                {
                    b.Navigation("facturas");

                    b.Navigation("ordenes_de_compras");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.departamento", b =>
                {
                    b.Navigation("ciudades");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.empleado", b =>
                {
                    b.Navigation("ordenes_de_compras");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.empresa", b =>
                {
                    b.Navigation("tienda");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.factura", b =>
                {
                    b.Navigation("metodos_de_pagos");

                    b.Navigation("ordenes_de_compras");

                    b.Navigation("productos");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.ordenes_de_compra", b =>
                {
                    b.Navigation("ordenes_productos");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.paise", b =>
                {
                    b.Navigation("departamentos");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.producto", b =>
                {
                    b.Navigation("alertas_stocks");

                    b.Navigation("historial_inventarios");

                    b.Navigation("inventario");

                    b.Navigation("ordenes_productos");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.proveedore", b =>
                {
                    b.Navigation("productos");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.role", b =>
                {
                    b.Navigation("usuarios");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.sub_categoria", b =>
                {
                    b.Navigation("productos");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.tienda", b =>
                {
                    b.Navigation("empleados");

                    b.Navigation("productos");
                });

            modelBuilder.Entity("SionFashioWebApplicationMVC.Models.usuario", b =>
                {
                    b.Navigation("registros_actividades");
                });
#pragma warning restore 612, 618
        }
    }
}
